### ISSUE TITLE
Feature request: custom timers

### ISSUE THREAD

**Issue by fruch** [jaimebuelta/gorgon#1]
A way to report more then one time per run
For example having 3 http requests that depend on each other
And have a way to report time took for each of them

**Comment by jaimebuelta** [comment]
This is an interesting thing.

I think it will be possible to do something like:

```
def task(number):
   with Gorgon.measurement('subtask1'):
       result = request.get(A)
   process_result(result)
   with Gorgon.measurement('subtask2'):
       result = request.get(B)
    process_result(result)
```

  And then report subtask1 and subtask2 times.

 I'll give it a thought and see how can it be implemented...

  Thanks!

**Comment by jaimebuelta** [comment]
Hey,

  I've pushed a commit implementing this.

  Cheers!
